const fs = require('fs');

let cookieContent = `[
  {
    "domain": ".youtube.com",
    "expirationDate": 1735689600,
    "hostOnly": false,
    "httpOnly": true,
    "name": "LOGIN_INFO",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "AFmm",
    "id": 1
  }
]`;

if (cookieContent.startsWith('[')) {
    try {
        const jsonCookies = JSON.parse(cookieContent);
        let netscapeCookies = "# Netscape HTTP Cookie File\n# https://curl.haxx.se/docs/http-cookies.html\n# This file was generated by yt-dlp!\n\n";
        jsonCookies.forEach(c => {
            const domain = c.domain || '';
            const includeSubDomain = domain.startsWith('.') ? 'TRUE' : 'FALSE';
            const path = c.path || '/';
            const secure = c.secure ? 'TRUE' : 'FALSE';
            const expiry = c.expirationDate ? Math.round(c.expirationDate) : (c.expiry ? Math.round(c.expiry) : 0);
            const name = c.name;
            const value = c.value;
            netscapeCookies += `${domain}\t${includeSubDomain}\t${path}\t${secure}\t${expiry}\t${name}\t${value}\n`;
        });
        cookieContent = netscapeCookies;
    } catch (e) {
        console.log("Error:", e);
    }
}
console.log(cookieContent);
