name: Parse User Links Worker

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email của người dùng'
        required: true

jobs:
  run-parse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install Dependencies
      run: |
        cd "Tool-Thread"/tele_bot && npm install && npm install @google/generative-ai

    - name: Run Parse Links Script
      env:
        USER_EMAIL: ${{ github.event.inputs.email }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        TELE_BOT_TOKEN: ${{ secrets.TELE_BOT_TOKEN }}
        SHOPEE_COOKIE: ${{ secrets.SHOPEE_COOKIE }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GEMINI_API_KEY_2: ${{ secrets.GEMINI_API_KEY_2 }}
        GEMINI_API_KEY_3: ${{ secrets.GEMINI_API_KEY_3 }}
      run: |
        cd "Tool-Thread"/tele_bot && node fb_bot/5_shopee_bulk_scraper.js
